# time for my aliases...
alias c='clear'
alias h='cd $HOME'

alias ga='git add'
alias gbl='git blame'
alias gb='git branch'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gfp='git fetch --prune'
alias gl='git log'
alias gm='git merge'
alias gpl='git pull'
alias gr='git rebase'
alias gres='git reset'
alias gps='git push'
alias gs='git status'
alias gsa='git stash apply'
alias gst='git stash'
alias gsp='git stash pop'

alias sa='source activate'

alias vi='nvim'
alias vim='nvim'
